services:
    web:
        build:
            target: web
            context: .
        env_file:
            - .env
        ports:
            - "8000:80"
        volumes:
            - .:/var/www/html
        depends_on:
            - db
        container_name: ${APP_NAME}
        command: /bin/sh -c "composer install && apache2-foreground"
        networks:
            - mynetwork

    db:
        image: mysql:latest
        env_file:
            - .env
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
        ports:
            - "3306:3306"
        networks:
            - mynetwork
    phpmyadmin:
        image: 'phpmyadmin/phpmyadmin:latest'
        container_name: phpmyadmin_service
        restart: always
        ports:
            - '9889:80'
        environment:
            PMA_HOST: db
        depends_on:
            - db
        networks:
            - mynetwork

volumes:
    dbdata:
networks:
    mynetwork:
        driver: bridge
